name: jwk
version: 0.1.0
homepage: https://github.com/dint-dev/cryptography
description: JWK (JSON Web Key) encoding and decoding (for package:cryptography).

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  cryptography: 
    git:
      url: https://github.com/kenta-wakasa/cryptography
      path: cryptography

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0

dependency_overrides:
  cryptography:
    path: ../cryptography