name: Dart CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        sdk: [stable, beta, dev]
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Run tests (cryptography)
        run: dart test --platform vm
        working-directory: ./cryptography
      - name: Run tests (jwk)
        run: dart test --platform vm
        working-directory: ./jwk
      - name: Analyze (cryptography)
        run: dart analyze
        working-directory: ./cryptography
      - name: Analyze (jwk)
        run: dart analyze
        working-directory: ./jwk